"""Add genre

Revision ID: 61cef5b1ea8d
Revises: 915e637fcb53
Create Date: 2026-01-23 09:57:25.820859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cef5b1ea8d'
down_revision: Union[str, Sequence[str], None] = '915e637fcb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
